add package.json -- cordova 7.0.0
VersoSolutions/CordovaClipboard pull request #27
Opened 2017-05-08 10:28 UTC by tgensol

Cordova 7.0.0 is now asking for a package.json file

2017-05-08 23:34 UTC, patrickbussmann commented
See https://cordova.apache.org/news/2017/05/04/cordova-7.html.
And https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/#publishing-plugins.

Thanks :+1:

2017-05-08 23:35 UTC, patrickbussmann requested changes
Wrong repository url given!

2017-05-08 23:35 UTC, patrickbussmann commented on package.json
> +    "url": "git+https://github.com/tgensol/CordovaClipboard.git"
@@tgensol please change to "VersoSolutions" instead "tgensol". :+1:

2017-05-08 23:35 UTC, patrickbussmann commented on package.json
> +    "url": "https://github.com/tgensol/CordovaClipboard/issues"
@@tgensol please change to "VersoSolutions" instead "tgensol". :+1:

2017-05-08 23:35 UTC, patrickbussmann commented on package.json
> +  "homepage": "https://github.com/tgensol/CordovaClipboard#readme"
@@tgensol please change to "VersoSolutions" instead "tgensol". :+1:

2017-05-09 12:05 UTC, tgensol commented
@patrickbussmann done thanks

2017-05-24 17:28 UTC, ibnclaudius commented
Any idea when this will be released?

2017-06-03 15:08 UTC, piotrowski commented
PR looks good, lgtm!

2017-06-06 19:47 UTC, ibnclaudius commented
As the last commit was over 3 years ago and the project seems completely abandoned, I've created a new one with the fixes. https://github.com/ibnclaudius/CordovaClipboard

2017-10-28 18:50 UTC, mreis1 approved these changes

2024-10-22 09:25 UTC, closed without merging